"use client";

import { useState } from "react";
import { SyllabusCard } from "./SyllabusCard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

interface CardData {
  id: string;
  title: string;
  type: "display" | "quiz" | "cheatsheet" | "activity" | "case-study" | "debate" | "reading" | "video" | "project";
  module: number;
  description: string;
  duration?: string;
  difficulty?: "beginner" | "intermediate" | "advanced";
  tags?: string[];
}

const expandedSyllabusCards: CardData[] = [
  // Module 6: Accountability, Liability, and Professional Responsibility (35 cards)
  {
    id: "m6-1",
    title: "Liability Layers in AI Systems",
    type: "display",
    module: 6,
    description: "Comprehensive analysis of liability layers across the AI ecosystem, examining how responsibility is distributed among developers, deployers, procurers, and professional end-users. This card explores the complex web of legal obligations, contractual relationships, and regulatory requirements that determine who bears responsibility when AI systems cause harm. We analyze emerging legal frameworks and court decisions that are reshaping liability landscapes in the AI era.",
    duration: "35 min",
    difficulty: "intermediate",
    tags: ["liability", "responsibility", "legal-frameworks", "ecosystem"]
  },
  {
    id: "m6-2",
    title: "Developer Liability Frameworks",
    type: "case-study",
    module: 6,
    description: "Detailed examination of developer liability in AI systems, covering product liability, negligence claims, and emerging statutory obligations. Analyzes cases where AI developers have been held accountable for system failures, bias issues, and inadequate safety measures. Examines how liability frameworks are evolving to address unique AI development challenges.",
    duration: "40 min",
    difficulty: "intermediate",
    tags: ["case-study", "developer-liability", "product-liability", "negligence"]
  },
  {
    id: "m6-3",
    title: "Deployer and Operator Responsibility",
    type: "display",
    module: 6,
    description: "Analysis of deployer and operator liability in AI systems, covering implementation decisions, monitoring obligations, and failure to maintain adequate oversight. Examines how organizations using AI systems are being held responsible for harms caused by inadequate deployment practices, insufficient monitoring, or failure to implement appropriate safeguards.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["deployer-liability", "operator-responsibility", "implementation", "monitoring"]
  },
  {
    id: "m6-4",
    title: "Procurement and Supply Chain Liability",
    type: "display",
    module: 6,
    description: "Examination of liability issues in AI procurement and supply chains, covering due diligence requirements, vendor selection, and contractual risk allocation. Analyzes how organizations are being held responsible for AI systems they acquire or integrate, even when developed by third parties.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["procurement", "supply-chain", "due-diligence", "vendor-management"]
  },
  {
    id: "m6-5",
    title: "Professional End-User Responsibility",
    type: "case-study",
    module: 6,
    description: "Analysis of professional responsibility for AI use in regulated professions, including legal, medical, financial, and engineering fields. Examines how courts and professional bodies are redefining standards of care when professionals use AI tools in their practice.",
    duration: "35 min",
    difficulty: "intermediate",
    tags: ["case-study", "professional-responsibility", "regulated-professions", "standards-of-care"]
  },
  {
    id: "m6-6",
    title: "AI in Legal Practice: Mata v Avianca",
    type: "case-study",
    module: 6,
    description: "In-depth analysis of the landmark Mata v Avianca case where lawyers submitted hallucinated legal citations generated by ChatGPT. This early warning case demonstrated the risks of AI use in legal practice and established precedents for professional responsibility in AI-assisted work.",
    duration: "40 min",
    difficulty: "intermediate",
    tags: ["case-study", "Mata-v-Avianca", "legal-ethics", "hallucinations", "professional-responsibility"]
  },
  {
    id: "m6-7",
    title: "Hallucination Litigation Explosion 2025-2026",
    type: "case-study",
    module: 6,
    description: "Analysis of the dramatic escalation in hallucination-related litigation from 2025-2026, examining hundreds of sanctions decisions, disqualification proceedings, and bar referrals. Explores how courts are developing standards for AI verification and professional responsibility.",
    duration: "45 min",
    difficulty: "advanced",
    tags: ["case-study", "hallucination-litigation", "sanctions", "disqualification", "bar-referrals"]
  },
  {
    id: "m6-8",
    title: "Wadsworth v Walmart Internal AI Case",
    type: "case-study",
    module: 6,
    description: "Examination of the Wadsworth v Walmart case showing hallucination risks even in domain-specific internal AI tools. Demonstrates that AI reliability issues persist across applications and contexts, creating liability risks for internal system deployments.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["case-study", "Wadsworth-v-Walmart", "internal-AI", "hallucinations", "domain-specific"]
  },
  {
    id: "m6-9",
    title: "Professional Duty to Verify AI Output",
    type: "display",
    module: 6,
    description: "Analysis of emerging professional duties to verify AI-generated content and recommendations. Examines how courts and regulators are redefining 'reasonable care' standards to include AI verification requirements across different professions.",
    duration: "35 min",
    difficulty: "intermediate",
    tags: ["verification", "professional-duty", "reasonable-care", "AI-verification"]
  },
  {
    id: "m6-10",
    title: "Reasonable Care Standards Evolution",
    type: "display",
    module: 6,
    description: "Examination of how negligence standards are evolving to address AI use in professional contexts. Analyzes court decisions, regulatory guidance, and professional ethics opinions that are reshaping what constitutes reasonable care in the AI era.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["reasonable-care", "negligence-standards", "evolution", "AI-era"]
  },
  {
    id: "m6-11",
    title: "Disciplinary Hearing Simulation",
    type: "activity",
    module: 6,
    description: "Role-playing exercise simulating a disciplinary hearing for AI-related professional misconduct. Participants take roles as bar regulators, counsel using AI, and expert witnesses to argue whether sanctions or disqualification are warranted.",
    duration: "70 min",
    difficulty: "advanced",
    tags: ["activity", "disciplinary-hearing", "role-play", "professional-misconduct", "sanctions"]
  },
  {
    id: "m6-12",
    title: "Bar Regulatory Perspectives",
    type: "display",
    module: 6,
    description: "Analysis of how bar associations and legal regulators are approaching AI use in legal practice. Examines new guidelines, enforcement priorities, and disciplinary procedures being developed to address AI-related misconduct.",
    duration: "25 min",
    difficulty: "intermediate",
    tags: ["bar-regulation", "legal-ethics", "guidelines", "enforcement"]
  },
  {
    id: "m6-13",
    title: "Medical AI Liability Cases",
    type: "case-study",
    module: 6,
    description: "Examination of liability cases involving AI in medical practice, including diagnostic errors, treatment recommendations, and surgical assistance. Analyzes how medical malpractice standards are adapting to AI-assisted healthcare.",
    duration: "35 min",
    difficulty: "intermediate",
    tags: ["case-study", "medical-AI", "malpractice", "diagnostic-errors", "healthcare"]
  },
  {
    id: "m6-14",
    title: "Financial Services AI Liability",
    type: "case-study",
    module: 6,
    description: "Analysis of liability issues in AI-driven financial services, including algorithmic trading, credit decisions, and fraud detection. Examines regulatory enforcement and civil litigation trends in fintech AI applications.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["case-study", "financial-services", "algorithmic-trading", "credit-decisions", "fintech"]
  },
  {
    id: "m6-15",
    title: "Engineering Professional Responsibility",
    type: "display",
    module: 6,
    description: "Examination of professional responsibility for engineers developing and deploying AI systems. Analyzes how engineering codes of ethics are being updated to address AI-specific challenges and liability risks.",
    duration: "25 min",
    difficulty: "intermediate",
    tags: ["engineering", "professional-responsibility", "codes-of-ethics", "AI-specific-challenges"]
  },
  {
    id: "m6-16",
    title: "AI-Specific Standard of Care Debate",
    type: "debate",
    module: 6,
    description: "Structured debate on whether professions need AI-specific standards of care embedded in their codes of ethics, or whether general negligence standards are sufficient. Examines arguments for and against specialized AI competence requirements.",
    duration: "50 min",
    difficulty: "advanced",
    tags: ["debate", "standard-of-care", "AI-specific", "professional-ethics", "competence"]
  },
  {
    id: "m6-17",
    title: "Arguments for AI-Specific Standards",
    type: "display",
    module: 6,
    description: "Analysis of arguments supporting AI-specific standards of care in professional practice. Examines unique AI risks, verification challenges, and the need for specialized expertise in different professional contexts.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["AI-specific-standards", "professional-competence", "risk-management", "verification"]
  },
  {
    id: "m6-18",
    title: "Arguments Against AI-Specific Standards",
    type: "display",
    module: 6,
    description: "Examination of arguments against creating AI-specific standards of care, focusing on flexibility, rapid technological change, and the adequacy of existing negligence frameworks. Analyzes potential unintended consequences.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["general-negligence", "flexibility", "technological-change", "unintended-consequences"]
  },
  {
    id: "m6-19",
    title: "Insurance and AI Liability",
    type: "display",
    module: 6,
    description: "Analysis of how insurance markets are responding to AI liability risks, including professional liability policies, cyber insurance, and emerging AI-specific coverage products. Examines coverage gaps and underwriting challenges.",
    duration: "25 min",
    difficulty: "intermediate",
    tags: ["insurance", "liability-coverage", "cyber-insurance", "risk-transfer"]
  },
  {
    id: "m6-20",
    title: "Contractual Risk Allocation",
    type: "cheatsheet",
    module: 6,
    description: "Practical guide to allocating AI risks through contracts, including indemnification clauses, limitation of liability, warranty representations, and insurance requirements. Templates and best practices included.",
    duration: "20 min",
    difficulty: "intermediate",
    tags: ["cheatsheet", "contracts", "risk-allocation", "indemnification", "warranties"]
  },
  {
    id: "m6-21",
    title: "Regulatory Enforcement Trends",
    type: "display",
    module: 6,
    description: "Analysis of regulatory enforcement trends in AI-related professional misconduct, including agency priorities, enforcement patterns, and penalty trends. Examines coordination between regulators and professional bodies.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["regulatory-enforcement", "professional-misconduct", "agency-priorities", "penalties"]
  },
  {
    id: "m6-22",
    title: "Cross-Border Liability Issues",
    type: "display",
    module: 6,
    description: "Examination of cross-border liability issues in AI systems, including jurisdictional conflicts, choice of law considerations, and enforcement challenges. Analyzes international liability frameworks and cooperation mechanisms.",
    duration: "30 min",
    difficulty: "advanced",
    tags: ["cross-border", "jurisdiction", "choice-of-law", "international-cooperation"]
  },
  {
    id: "m6-23",
    title: "AI Product Liability Evolution",
    type: "case-study",
    module: 6,
    description: "Analysis of how traditional product liability law is evolving to address AI systems, including defect definitions, causation challenges, and damage assessment. Examines landmark cases and statutory developments.",
    duration: "35 min",
    difficulty: "intermediate",
    tags: ["case-study", "product-liability", "defects", "causation", "damage-assessment"]
  },
  {
    id: "m6-24",
    title: "Vicarious Liability in AI Context",
    type: "display",
    module: 6,
    description: "Examination of vicarious liability principles as applied to AI systems, including employer responsibility for employee AI use and organizational liability for contractor AI implementations.",
    duration: "25 min",
    difficulty: "intermediate",
    tags: ["vicarious-liability", "employer-responsibility", "contractor-liability", "organizational-risk"]
  },
  {
    id: "m6-25",
    title: "Professional Liability Insurance",
    type: "display",
    module: 6,
    description: "Analysis of professional liability insurance coverage for AI-related risks, including policy exclusions, coverage triggers, and claims handling. Examines how insurers are responding to AI adoption in professional services.",
    duration: "25 min",
    difficulty: "intermediate",
    tags: ["professional-liability", "insurance-coverage", "policy-exclusions", "claims-handling"]
  },
  {
    id: "m6-26",
    title: "AI Ethics and Legal Compliance",
    type: "display",
    module: 6,
    description: "Analysis of the intersection between AI ethics guidelines and legal compliance requirements. Examines how ethical principles are being incorporated into legal standards and professional obligations.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["AI-ethics", "legal-compliance", "ethical-principles", "professional-obligations"]
  },
  {
    id: "m6-27",
    title: "Risk Management Frameworks",
    type: "cheatsheet",
    module: 6,
    description: "Comprehensive guide to implementing risk management frameworks for AI liability, including risk assessment, mitigation strategies, monitoring procedures, and incident response plans.",
    duration: "20 min",
    difficulty: "intermediate",
    tags: ["cheatsheet", "risk-management", "risk-assessment", "mitigation", "incident-response"]
  },
  {
    id: "m6-28",
    title: "Documentation for Liability Defense",
    type: "activity",
    module: 6,
    description: "Hands-on exercise creating documentation strategies to defend against AI liability claims. Learn to maintain audit trails, decision logs, and compliance records that demonstrate reasonable care.",
    duration: "45 min",
    difficulty: "intermediate",
    tags: ["activity", "documentation", "liability-defense", "audit-trails", "compliance-records"]
  },
  {
    id: "m6-29",
    title: "Expert Witness Testimony",
    type: "display",
    module: 6,
    description: "Analysis of expert witness testimony in AI liability cases, including qualification standards, testimony content, and evidentiary challenges. Examines the role of technical experts in AI litigation.",
    duration: "25 min",
    difficulty: "intermediate",
    tags: ["expert-witness", "testimony", "qualification", "evidence", "AI-litigation"]
  },
  {
    id: "m6-30",
    title: "Class Actions in AI Cases",
    type: "case-study",
    module: 6,
    description: "Examination of class action litigation involving AI systems, including certification challenges, damage calculation, and settlement strategies. Analyzes emerging trends in AI-related class actions.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["case-study", "class-actions", "certification", "damages", "settlements"]
  },
  {
    id: "m6-31",
    title: "Regulatory Investigation Response",
    type: "activity",
    module: 6,
    description: "Simulation exercise responding to regulatory investigations of AI-related misconduct. Practice developing investigation strategies, document production, and negotiation approaches.",
    duration: "50 min",
    difficulty: "advanced",
    tags: ["activity", "regulatory-investigation", "document-production", "negotiation"]
  },
  {
    id: "m6-32",
    title: "International Liability Harmonization",
    type: "display",
    module: 6,
    description: "Analysis of efforts to harmonize AI liability standards internationally, including convention proposals, model laws, and regulatory cooperation. Examines challenges and progress in global harmonization.",
    duration: "30 min",
    difficulty: "advanced",
    tags: ["international-harmonization", "conventions", "model-laws", "regulatory-cooperation"]
  },
  {
    id: "m6-33",
    title: "Module 6 Assessment",
    type: "quiz",
    module: 6,
    description: "Comprehensive assessment covering liability frameworks, professional responsibility, hallucination litigation, verification duties, and risk management strategies.",
    duration: "45 min",
    difficulty: "intermediate",
    tags: ["quiz", "assessment", "module-6", "liability", "professional-responsibility"]
  },
  {
    id: "m6-34",
    title: "Liability Risk Assessment Project",
    type: "project",
    module: 6,
    description: "Capstone project conducting a comprehensive liability risk assessment for an AI system, including risk identification, mitigation planning, and documentation strategy development.",
    duration: "90 min",
    difficulty: "advanced",
    tags: ["project", "liability-assessment", "risk-mitigation", "documentation-strategy"]
  },
  {
    id: "m6-35",
    title: "Professional Ethics Policy Development",
    type: "project",
    module: 6,
    description: "Project developing comprehensive professional ethics policies for AI use in a specific professional context, including guidelines, training programs, and enforcement procedures.",
    duration: "85 min",
    difficulty: "advanced",
    tags: ["project", "ethics-policy", "guidelines", "training", "enforcement"]
  },

  // Module 7: Sectoral Governance Case Studies (35 cards)
  {
    id: "m7-1",
    title: "Finance Sector AI Governance",
    type: "display",
    module: 7,
    description: "Comprehensive analysis of AI governance in the financial sector, covering algorithmic trading, credit scoring, fraud detection, and customer service applications. This card examines how financial regulators are developing AI-specific frameworks, addressing systemic risks, and ensuring market integrity. We explore the unique challenges of governing AI in high-stakes financial environments where decisions have immediate economic consequences.",
    duration: "40 min",
    difficulty: "intermediate",
    tags: ["finance", "algorithmic-trading", "credit-scoring", "fraud-detection", "regulatory-frameworks"]
  },
  {
    id: "m7-2",
    title: "AI-Driven Pricing and Antitrust",
    type: "case-study",
    module: 7,
    description: "Detailed examination of antitrust concerns in AI-driven pricing algorithms, including price discrimination, collusion detection, and market manipulation. Analyzes enforcement actions and regulatory approaches to algorithmic competition issues.",
    duration: "35 min",
    difficulty: "intermediate",
    tags: ["case-study", "antitrust", "pricing-algorithms", "price-discrimination", "market-manipulation"]
  },
  {
    id: "m7-3",
    title: "Credit Scoring AI and Fairness",
    type: "case-study",
    module: 7,
    description: "Analysis of AI systems in credit scoring and lending decisions, examining fairness requirements, transparency obligations, and regulatory compliance. Explores how AI is changing credit assessment and the governance challenges this creates.",
    duration: "35 min",
    difficulty: "intermediate",
    tags: ["case-study", "credit-scoring", "fairness", "transparency", "regulatory-compliance"]
  },
  {
    id: "m7-4",
    title: "Financial AI Auditability Requirements",
    type: "display",
    module: 7,
    description: "Examination of auditability requirements for financial AI systems, including model validation, documentation standards, and regulatory reporting. Analyzes how financial institutions are implementing governance frameworks for AI.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["auditability", "model-validation", "documentation", "regulatory-reporting"]
  },
  {
    id: "m7-5",
    title: "Healthcare AI High-Risk Classification",
    type: "case-study",
    module: 7,
    description: "In-depth analysis of healthcare AI systems under high-risk classification frameworks, covering diagnostic tools, treatment recommendations, and clinical decision support. Examines validation requirements, post-market surveillance, and liability issues.",
    duration: "40 min",
    difficulty: "intermediate",
    tags: ["case-study", "healthcare-AI", "diagnostic-tools", "validation", "post-market-surveillance"]
  },
  {
    id: "m7-6",
    title: "Medical AI Validation Requirements",
    type: "display",
    module: 7,
    description: "Comprehensive overview of validation requirements for medical AI systems, including clinical trials, performance testing, and regulatory approval processes. Analyzes differences between jurisdictions and emerging standards.",
    duration: "35 min",
    difficulty: "intermediate",
    tags: ["medical-AI", "validation", "clinical-trials", "regulatory-approval", "standards"]
  },
  {
    id: "m7-7",
    title: "Post-Market Surveillance for Health AI",
    type: "display",
    module: 7,
    description: "Analysis of post-market surveillance requirements for healthcare AI systems, including performance monitoring, adverse event reporting, and update management. Examines how medical device regulations apply to AI.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["post-market-surveillance", "performance-monitoring", "adverse-events", "medical-devices"]
  },
  {
    id: "m7-8",
    title: "Platform and Media AI Governance",
    type: "display",
    module: 7,
    description: "Examination of AI governance in platform and media companies, covering content moderation, recommendation systems, and deepfake detection. Analyzes state-level regulations and platform self-governance approaches.",
    duration: "35 min",
    difficulty: "intermediate",
    tags: ["platforms", "media", "content-moderation", "recommendation-systems", "deepfakes"]
  },
  {
    id: "m7-9",
    title: "Deepfake Regulation at State Level",
    type: "case-study",
    module: 7,
    description: "Analysis of state-level deepfake regulations in the US, covering synthetic media labeling, non-consensual imagery bans, and political deepfake restrictions. Examines enforcement challenges and platform compliance.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["case-study", "deepfakes", "synthetic-media", "state-regulations", "platform-compliance"]
  },
  {
    id: "m7-10",
    title: "Content Moderation AI Systems",
    type: "display",
    module: 7,
    description: "Overview of AI systems used for content moderation, including automated detection, context analysis, and appeal mechanisms. Examines accuracy, bias, and transparency issues in moderation AI.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["content-moderation", "automated-detection", "context-analysis", "appeal-mechanisms"]
  },
  {
    id: "m7-11",
    title: "Synthetic Content Labeling Requirements",
    type: "cheatsheet",
    module: 7,
    description: "Practical guide to synthetic content labeling requirements across different jurisdictions, including technical standards, implementation challenges, and enforcement mechanisms.",
    duration: "20 min",
    difficulty: "intermediate",
    tags: ["cheatsheet", "synthetic-content", "labeling", "technical-standards", "implementation"]
  },
  {
    id: "m7-12",
    title: "Public Sector AI Governance",
    type: "display",
    module: 7,
    description: "Analysis of AI governance in public sector applications, including policing, welfare systems, immigration, and administrative decision-making. Examines bans, moratoria, and special requirements for government AI use.",
    duration: "35 min",
    difficulty: "intermediate",
    tags: ["public-sector", "government-AI", "policing", "welfare", "immigration"]
  },
  {
    id: "m7-13",
    title: "AI in Policing and Law Enforcement",
    type: "case-study",
    module: 7,
    description: "Examination of AI applications in policing, including facial recognition, predictive policing, and crime analysis. Analyzes civil liberties concerns, accuracy issues, and regulatory responses.",
    duration: "35 min",
    difficulty: "intermediate",
    tags: ["case-study", "policing", "facial-recognition", "predictive-policing", "civil-liberties"]
  },
  {
    id: "m7-14",
    title: "Welfare System AI Applications",
    type: "case-study",
    module: 7,
    description: "Analysis of AI systems in welfare and benefits administration, covering eligibility determination, fraud detection, and resource allocation. Examines accuracy, fairness, and due process concerns.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["case-study", "welfare-systems", "benefits-administration", "fraud-detection", "due-process"]
  },
  {
    id: "m7-15",
    title: "Immigration AI Decision Systems",
    type: "display",
    module: 7,
    description: "Overview of AI systems in immigration processing, including visa screening, asylum assessments, and risk analysis. Examines transparency, accountability, and appeals mechanisms.",
    duration: "25 min",
    difficulty: "intermediate",
    tags: ["immigration", "visa-screening", "asylum-assessments", "risk-analysis", "appeals"]
  },
  {
    id: "m7-16",
    title: "Government AI Procurement Rules",
    type: "display",
    module: 7,
    description: "Analysis of government AI procurement requirements, including vendor vetting, compliance verification, and performance monitoring. Examines how governments are using procurement to enforce AI standards.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["procurement", "government-contracting", "vendor-vetting", "compliance-verification"]
  },
  {
    id: "m7-17",
    title: "Sector Pod Project Structure",
    type: "activity",
    module: 7,
    description: "Introduction to the sector pod project structure, where learners work in groups to analyze governance challenges in specific sectors. Explains project deliverables, timelines, and evaluation criteria.",
    duration: "25 min",
    difficulty: "beginner",
    tags: ["activity", "project-structure", "sector-analysis", "deliverables", "evaluation"]
  },
  {
    id: "m7-18",
    "title": "Finance Sector Governance Stack",
    type: "activity",
    module: 7,
    description: "Group project analyzing a high-profile finance AI misdeployment or controversy. Teams reconstruct the minimal governance stack that should have been in place, including internal policies, external obligations, audits, and crisis response plans.",
    duration: "80 min",
    difficulty: "intermediate",
    tags: ["activity", "finance-sector", "governance-stack", "crisis-response", "policy-development"]
  },
  {
    id: "m7-19",
    title: "Healthcare Sector Governance Analysis",
    type: "activity",
    module: 7,
    description: "Group project examining healthcare AI governance failures and developing comprehensive governance frameworks. Teams analyze real cases and design improved governance structures.",
    duration: "85 min",
    difficulty: "intermediate",
    tags: ["activity", "healthcare-sector", "governance-failure", "framework-design", "improvement"]
  },
  {
    id: "m7-20",
    title: "Platform Governance Case Study",
    type: "activity",
    module: 7,
    description: "Group analysis of platform AI governance challenges, focusing on content moderation, recommendation systems, or synthetic media. Teams develop comprehensive governance solutions.",
    duration: "80 min",
    difficulty: "intermediate",
    tags: ["activity", "platform-governance", "content-moderation", "recommendation-systems", "solutions"]
  },
  {
    id: "m7-21",
    title: "Public Sector AI Governance Project",
    type: "activity",
    module: 7,
    description: "Group project analyzing public sector AI governance challenges, examining specific government applications and developing improved governance frameworks.",
    duration: "85 min",
    difficulty: "intermediate",
    tags: ["activity", "public-sector", "government-AI", "governance-improvement", "framework-development"]
  },
  {
    id: "m7-22",
    title: "Sector-Specific Risk Assessment",
    type: "activity",
    module: 7,
    description: "Hands-on exercise conducting sector-specific risk assessments for AI systems. Learn to identify unique risks, evaluate impacts, and design mitigation strategies for different sectors.",
    duration: "50 min",
    difficulty: "intermediate",
    tags: ["activity", "risk-assessment", "sector-specific", "mitigation-strategies"]
  },
  {
    id: "m7-23",
    title: "Government vs Private Sector Regulation Debate",
    type: "debate",
    module: 7,
    description: "Structured debate on whether government use of AI should be more tightly regulated than private-sector use. Examines arguments for and against differential regulatory treatment, considering innovation, public trust, and fundamental rights.",
    duration: "50 min",
    difficulty: "advanced",
    tags: ["debate", "government-regulation", "private-sector", "innovation", "public-trust"]
  },
  {
    id: "m7-24",
    title: "Arguments for Stricter Government Regulation",
    type: "display",
    module: 7,
    description: "Analysis of arguments supporting stricter regulation of government AI use, including public interest, fundamental rights, accountability concerns, and the need for higher standards in public services.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["government-regulation", "public-interest", "fundamental-rights", "accountability"]
  },
  {
    id: "m7-25",
    title: "Arguments Against Differential Treatment",
    type: "display",
    module: 7,
    description: "Examination of arguments against differential regulatory treatment of government vs private sector AI, including innovation concerns, efficiency benefits, and consistency in governance approaches.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["private-sector", "innovation", "efficiency", "regulatory-consistency"]
  },
  {
    id: "m7-26",
    title: "Sectoral Compliance Frameworks",
    type: "cheatsheet",
    module: 7,
    description: "Comprehensive guide to sector-specific AI compliance frameworks, including financial services, healthcare, platform, and public sector requirements. Templates and implementation guidance included.",
    duration: "25 min",
    difficulty: "intermediate",
    tags: ["cheatsheet", "sectoral-compliance", "frameworks", "implementation-guidance"]
  },
  {
    id: "m7-27",
    title: "Cross-Sector Learning and Transfer",
    type: "display",
    module: 7,
    description: "Analysis of how governance lessons can be transferred across sectors, examining common challenges, best practices, and adaptation strategies for different contexts.",
    duration: "25 min",
    difficulty: "intermediate",
    tags: ["cross-sector", "knowledge-transfer", "best-practices", "adaptation"]
  },
  {
    id: "m7-28",
    title: "Sector-Specific AI Standards",
    type: "reading",
    module: 7,
    description: "Survey of sector-specific AI standards and certifications, including ISO standards for medical AI, financial services guidelines, and platform governance frameworks.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["reading", "sector-standards", "certifications", "ISO", "guidelines"]
  },
  {
    id: "m7-29",
    title: "Industry Self-Regulation Initiatives",
    type: "case-study",
    module: 7,
    description: "Examination of industry self-regulation initiatives across different sectors, including consortium standards, voluntary commitments, and best practice guidelines.",
    duration: "30 min",
    difficulty: "intermediate",
    tags: ["case-study", "self-regulation", "industry-consortia", "voluntary-standards"]
  },
  {
    id: "m7-30",
    title: "Sectoral Enforcement Patterns",
    type: "display",
    module: 7,
    description: "Analysis of enforcement patterns across different sectors, examining regulatory priorities, penalty trends, and compliance challenges unique to each sector.",
    duration: "25 min",
    difficulty: "intermediate",
    tags: ["enforcement", "regulatory-priorities", "penalty-trends", "compliance-challenges"]
  },
  {
    id: "m7-31",
    title: "Sector-Specific Risk Metrics",
    type: "activity",
    module: 7,
    description: "Hands-on exercise developing sector-specific risk metrics for AI systems. Learn to identify key performance indicators, risk measures, and monitoring approaches for different sectors.",
    duration: "45 min",
    difficulty: "intermediate",
    tags: ["activity", "risk-metrics", "performance-indicators", "monitoring"]
  },
  {
    id: "m7-32",
    title: "Crisis Response Planning by Sector",
    type: "activity",
    module: 7,
    description: "Group exercise developing sector-specific crisis response plans for AI failures. Learn to design incident response, communication strategies, and remediation procedures.",
    duration: "50 min",
    difficulty: "intermediate",
    tags: ["activity", "crisis-response", "incident-response", "communication", "remediation"]
  },
  {
    id: "m7-33",
    title: "Module 7 Assessment",
    type: "quiz",
    module: 7,
    description: "Comprehensive assessment covering sectoral governance frameworks, finance applications, healthcare AI, platform governance, and public sector regulation.",
    duration: "45 min",
    difficulty: "intermediate",
    tags: ["quiz", "assessment", "module-7", "sectoral-governance"]
  },
  {
    id: "m7-34",
    title: "Sectoral Governance Implementation",
    type: "project",
    module: 7,
    description: "Capstone project implementing a comprehensive sectoral governance framework for an AI system, including sector-specific requirements, compliance procedures, and monitoring systems.",
    duration: "90 min",
    difficulty: "advanced",
    tags: ["project", "sectoral-governance", "implementation", "compliance", "monitoring"]
  },
  {
    id: "m7-35",
    title: "Cross-Sector Governance Analysis",
    type: "project",
    module: 7,
    description: "Research project comparing governance approaches across multiple sectors, identifying common challenges, best practices, and opportunities for cross-sector learning.",
    duration: "85 min",
    difficulty: "advanced",
    tags: ["project", "cross-sector-analysis", "comparative-study", "best-practices"]
  }
];

export function ExpandedSyllabusGrid() {
  const [selectedModule, setSelectedModule] = useState<number | null>(null);
  const [selectedType, setSelectedType] = useState<string | null>(null);

  const modules = Array.from({ length: 11 }, (_, i) => i);
  const types = ["display", "quiz", "cheatsheet", "activity", "case-study", "debate", "reading", "video", "project"];

  const filteredCards = expandedSyllabusCards.filter(card => {
    const moduleMatch = selectedModule === null || card.module === selectedModule;
    const typeMatch = selectedType === null || card.type === selectedType;
    return moduleMatch && typeMatch;
  });

  return (
    <div className="space-y-6">
      {/* Filters */}
      <div className="bg-white dark:bg-slate-800 rounded-lg p-6 shadow-lg">
        <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-4">
          Expanded AI Governance Syllabus (Modules 6-7)
        </h3>
        
        <div className="space-y-4">
          {/* Module Filter */}
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              Filter by Module
            </label>
            <div className="flex flex-wrap gap-2">
              <button
                onClick={() => setSelectedModule(null)}
                className={`px-3 py-1 rounded-full text-sm transition-colors ${
                  selectedModule === null
                    ? "bg-blue-600 text-white"
                    : "bg-gray-200 text-gray-700 hover:bg-gray-300"
                }`}
              >
                All Modules
              </button>
              {modules.map(module => (
                <button
                  key={module}
                  onClick={() => setSelectedModule(module)}
                  className={`px-3 py-1 rounded-full text-sm transition-colors ${
                    selectedModule === module
                      ? "bg-blue-600 text-white"
                      : "bg-gray-200 text-gray-700 hover:bg-gray-300"
                  }`}
                >
                  Module {module}
                </button>
              ))}
            </div>
          </div>

          {/* Type Filter */}
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              Filter by Card Type
            </label>
            <div className="flex flex-wrap gap-2">
              <button
                onClick={() => setSelectedType(null)}
                className={`px-3 py-1 rounded-full text-sm transition-colors ${
                  selectedType === null
                    ? "bg-purple-600 text-white"
                    : "bg-gray-200 text-gray-700 hover:bg-gray-300"
                }`}
              >
                All Types
              </button>
              {types.map(type => (
                <button
                  key={type}
                  onClick={() => setSelectedType(type)}
                  className={`px-3 py-1 rounded-full text-sm transition-colors ${
                    selectedType === type
                      ? "bg-purple-600 text-white"
                      : "bg-gray-200 text-gray-700 hover:bg-gray-300"
                  }`}
                >
                  {type.replace("-", " ").toUpperCase()}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Results Count */}
        <div className="mt-4 text-sm text-slate-600 dark:text-slate-400">
          Showing {filteredCards.length} cards
        </div>
      </div>

      {/* Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {filteredCards.map(card => (
          <SyllabusCard
            key={card.id}
            id={card.id}
            title={card.title}
            type={card.type}
            module={card.module}
            description={card.description}
            duration={card.duration}
            difficulty={card.difficulty}
            tags={card.tags}
            onClick={() => console.log(`Card ${card.id} clicked`)}
          />
        ))}
      </div>

      {/* Empty State */}
      {filteredCards.length === 0 && (
        <div className="text-center py-12">
          <p className="text-slate-600 dark:text-slate-400">
            No cards match your current filters. Try adjusting your selection.
          </p>
        </div>
      )}
    </div>
  );
}
